version: 2.0

jobs:
    build:
        docker:
            - image: python:3.6.4
        steps:
            - checkout
            - run:
                command: |
                    pip install -r requirements/testing.txt
                    make ci
